# -*- coding: utf-8 -*-
"""Mapas auto organizáveis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MmRnAHDksy_u-lgcDptszZmLiJaOD7_9
"""

!pip install minisom

import pandas as pd
from minisom import MiniSom
from sklearn.preprocessing import MinMaxScaler
from pylab import pcolor,colorbar,plot

data = pd.read_csv('wines.csv')
data.head()

data.shape

predictors = data.iloc[:,1:14].values
classes = data.iloc[:,0].values

normalized = MinMaxScaler(feature_range=(0,1))
predictors = normalized.fit_transform(predictors)

mini = MiniSom(x = 8,y = 8,sigma=0.1,input_len=13,learning_rate=0.5,random_seed=2)
mini.random_weights_init(predictors)

mini.train_random(data = predictors,num_iteration=100)
mini._weights

mini._activation_map

var = mini.activation_response(predictors)

pcolor(mini.distance_map().T)
colorbar()

markers = ['o','s','D']
colors = ['r','g','b']

w = mini.winner(predictors[2])
w

for i,x in enumerate(predictors):
  w = mini.winner(x)
  plot(w[0] + 0.5,w[1] + 0.5,markers[classes[i]],markerfacecolor='None',
       markersize=10,markeredgecolor=colors[classes[i]],markeredgewidth=2)